name: HardHat Build

on:
  push:
    branches: [main]
  schedule:
    - cron: "00 06 * * 1"

jobs:
  dchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Project
        run: |
          ./__install.sh
      - name: Run Project Test Suite
        env:
          SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          LOCAL_PRIVATE_KEY: ${{ secrets.LOCAL_PRIVATE_KEY }}
        run: |
          ./__dryrun.sh
